name: Check for Dist Changes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Check for Dist Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check for Dist Changes
        run: yarn start checkForDistChanges
