name: Jest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Jest
        run: yarn start test.withCoverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v2.0.2
        with:
          fail_ci_if_error: true
